[package]
name = "pb_udp_rust"
version = "0.1.0"
edition = "2021"
authors = ["Qi Xu"]

[dependencies]
prost = "0.12.6"
tokio = { version = "1", features = ["full"] }
rand = "0.8"

[build-dependencies]
prost-build = "0.12"